#!/bin/bash
# Generate an OVN-Kubernetes EgressFirewall for a codebox namespace from the
# same domain allowlists the in-container firewall uses
# (firewall-domains.txt + the harness overlays). This is the pod-level
# replacement for `--with-firewall`, which the apptainer runtime cannot
# provide (no NET_ADMIN in the pod).
#
#   k8s/gen-egress-firewall.sh [harness...] > egressfirewall.yaml
#   oc apply -n <namespace> -f egressfirewall.yaml
#
# With no argument all four harness overlays are included (one pod serves
# all launchers). Only one EgressFirewall per namespace is allowed, and it
# must be named "default". Cluster-internal traffic (DNS, the image
# registry, the API) is not subject to EgressFirewall rules; pulling the
# harness images from quay.io is, so quay.io and its CDN are added.
#
# Requires OVN-Kubernetes (the default network plugin on OpenShift 4.12+).
# Wildcard dnsName rules (*.example.com) need OpenShift 4.14+.

set -euo pipefail

REPO_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
harnesses=("$@")
[[ ${#harnesses[@]} -gt 0 ]] || harnesses=(claude opencode qwencode codex)

files=("${REPO_DIR}/firewall-domains.txt")
for h in "${harnesses[@]}"; do
    f="${REPO_DIR}/firewall-domains-${h}.txt"
    [[ -f "$f" ]] || { echo "No such harness domain file: $f" >&2; exit 1; }
    files+=("$f")
done

# Registry hosting the harness images (the SIF conversion pulls from it)
extra_domains=(quay.io cdn.quay.io cdn01.quay.io cdn02.quay.io cdn03.quay.io)

domains=$(
    { grep -hv '^\s*#' "${files[@]}" | sed 's/\s*#.*$//' ; printf '%s\n' "${extra_domains[@]}"; } \
        | sed 's/[[:space:]]//g' | sed '/^$/d' | LC_ALL=C sort -u
)

cat <<EOF
# Generated by k8s/gen-egress-firewall.sh from firewall-domains.txt and
# firewall-domains-{${harnesses[*]// /,}}.txt. Do not edit; regenerate.
apiVersion: k8s.ovn.org/v1
kind: EgressFirewall
metadata:
  name: default
spec:
  egress:
EOF
while IFS= read -r d; do
    [[ -n "$d" ]] || continue
    printf '    - type: Allow\n      to:\n        dnsName: %s\n' "$d"
done <<< "$domains"
cat <<EOF
    - type: Deny
      to:
        cidrSelector: 0.0.0.0/0
EOF
